version: '3.7'
services:
    service1:
        .....

    webapp:
        container_name: memos-reactive
        build: ./memos-reactive 
        ports:
            - "8000:80"
        labels:
            NAME: "memos-reactive"
        networks:
            - app-network
     
    service2:
        ....

networks:
    app-network:
        driver: bridge
